// src/lib/visuals/render-demo-media.tsx
import type { AgentDemoMedia, VisualAccent, VisualStyle } from './parse-visuals';

interface RenderDemoMediaProps {
  media: AgentDemoMedia;
  accent: VisualAccent;
  style: VisualStyle;
  agentName: string;
}

const ACCENT_TEXT: Record<VisualAccent, string> = {
  plasma: 'text-plasma',
  aurora: 'text-aurora',
  cyan: 'text-cyan',
  green: 'text-green',
};

const ACCENT_STROKE: Record<VisualAccent, string> = {
  plasma: 'stroke-plasma',
  aurora: 'stroke-aurora',
  cyan: 'stroke-cyan',
  green: 'stroke-green',
};

const ACCENT_GLOW: Record<VisualAccent, string> = {
  plasma: 'shadow-plasmaGlowSoft',
  aurora: 'shadow-auroraGlowSoft',
  cyan: 'shadow-cyanGlowSoft',
  green: 'shadow-greenGlow',
};

const WRAPPER =
  'relative aspect-video overflow-hidden rounded-md border border-border-subtle bg-surface';

function getInitials(name: string): string {
  const words = name.trim().split(/\s+/).slice(0, 2);
  const letters = words.map((w) => w.charAt(0)).join('');
  return letters.toUpperCase() || 'GA';
}

function AutoGeneratedMedia({
  accent,
  style,
  agentName,
}: {
  accent: VisualAccent;
  style: VisualStyle;
  agentName: string;
}) {
  const initials = getInitials(agentName);
  const strokeClass = ACCENT_STROKE[accent];
  const textClass = ACCENT_TEXT[accent];
  const glowClass = style === 'minimal' ? '' : ACCENT_GLOW[accent];

  return (
    <div
      className={`${WRAPPER} ${glowClass} flex items-center justify-center`.trim()}
      role="img"
      aria-label={`${agentName} preview`}
    >
      <svg
        viewBox="0 0 640 360"
        xmlns="http://www.w3.org/2000/svg"
        className="absolute inset-0 h-full w-full opacity-60"
        aria-hidden="true"
      >
        <defs>
          <pattern id="grid-auto" width="32" height="32" patternUnits="userSpaceOnUse">
            <path
              d="M 32 0 L 0 0 0 32"
              fill="none"
              className={strokeClass}
              strokeWidth="0.5"
              strokeOpacity="0.35"
            />
          </pattern>
        </defs>
        <rect width="640" height="360" fill="url(#grid-auto)" />
        <path
          d="M40,300 L200,300 L240,220 L380,220 L420,140 L600,140"
          fill="none"
          className={strokeClass}
          strokeWidth="1.5"
          strokeOpacity="0.85"
        />
      </svg>
      <span
        className={`relative font-display text-6xl tracking-tightest ${textClass} drop-shadow-sm`}
      >
        {initials}
      </span>
    </div>
  );
}

export function RenderDemoMedia({ media, accent, style, agentName }: RenderDemoMediaProps) {
  if (media.kind === 'auto_generate') {
    return <AutoGeneratedMedia accent={accent} style={style} agentName={agentName} />;
  }

  if (media.kind === 'video') {
    return (
      <div className={WRAPPER}>
        <video
          src={media.url}
          poster={media.poster}
          className="h-full w-full object-cover"
          muted
          loop
          playsInline
          autoPlay
          preload="metadata"
          aria-label={`${agentName} demo video`}
        />
      </div>
    );
  }

  return (
    <div className={WRAPPER}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={media.url}
        alt={`${agentName} demo ${media.kind}`}
        className="h-full w-full object-cover"
        loading="lazy"
        decoding="async"
      />
    </div>
  );
}
