import 'server-only';
import generated from '@/data/agents-index.generated.json';
import type { Agent } from './types';
import { parseVisuals } from './visuals/parse-visuals';

// Generated by scripts/build-agents-index.mjs at build time from
// xlOS/agents/*/grok-install.yaml. The pre* scripts in package.json
// keep this index fresh on every dev/build/test invocation.
function sanitize(agent: Agent): Agent {
  if (agent.visuals === undefined) return agent;
  const parsed = parseVisuals(agent.visuals);
  if (parsed === null) {
    const { visuals: _dropped, ...rest } = agent;
    return rest;
  }
  return { ...agent, visuals: parsed };
}

const AGENTS: Agent[] = (generated as unknown as Agent[]).map(sanitize);

export async function getAgents(): Promise<Agent[]> {
  return AGENTS;
}

export async function getAgentById(id: string): Promise<Agent | null> {
  const agents = await getAgents();
  return agents.find((a) => a.id === id) ?? null;
}

export async function getFeaturedAgents(limit = 3): Promise<Agent[]> {
  const agents = await getAgents();
  return [...agents]
    .sort((a, b) => {
      const fa = a.featured ? 1 : 0;
      const fb = b.featured ? 1 : 0;
      if (fa !== fb) return fb - fa;
      return b.installs - a.installs;
    })
    .slice(0, limit);
}

export async function getLatestAgents(limit = 6): Promise<Agent[]> {
  const agents = await getAgents();
  return [...agents]
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
    .slice(0, limit);
}
